name: gets_seller
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  shared_preferences: ^0.5.7+3
  http: ^0.12.1
  intl: ^0.16.1
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.7+1
  url_launcher: ^5.4.10
  expandable: ^4.1.4
  flutter_staggered_grid_view: ^0.3.0
  mapbox_gl:
    git: git://github.com/tobrun/flutter-mapbox-gl.git
  rxdart: ^0.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
